name: Linux

on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint
        run: swift format lint --recursive --configuration .swift-format --strict Sources Tests

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: swift:${{matrix.swift-version}}
    timeout-minutes: 30
    strategy:
      matrix:
        swift-version:
          - "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: swift --version
      - name: Test
        run: swift test
